In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
36   34  Female     Good        UG       Yes
41   23    Male     Good        PG       Yes
17   22  Female     Poor        UG       Yes
21   32    Male  Average        PG        No
4    16  Female  Average        UG        No

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [9]:
X_train

review education
0   Average    School
3      Good        PG
14     Poor        PG
33     Good        PG
43     Poor        PG
38     Good    School
29  Average        UG
41     Good        PG
23     Good    School
49     Good        UG
4   Average        UG
45     Poor        PG
48     Good        UG
31     Poor    School
20  Average    School
12     Poor    School
2      Good        PG
32  Average        UG
24  Average        PG
11     Good        UG
18     Good    School
46     Poor        PG
39     Poor        PG
40     Good    School
13  Average    School
16     Poor        UG
8   Average        UG
10     Good        UG
42     Good        PG
34  Average    School
1      Poor        UG
5   Average    School
28     Poor    School
37  Average        PG
19     Poor        PG
21  Average        PG
22     Poor        PG
6      Good    School
35     Poor    School
36     Good        UG

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [11]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [16]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

c:\Users\SC\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [17]:
X_train

array([[1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [2., 1.]])

In [18]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [19]:
X_train

array([[1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [2., 1.]])

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le = LabelEncoder()

In [22]:
le.fit(y_train)

LabelEncoder()

In [23]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [24]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [25]:
y_train

array([0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1])